serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = {{ .Envs.FRP_SERVER_PORT }}
auth.method = "token"
auth.token = "{{ .Envs.FRP_AUTH_TOKEN }}"
transport.tls.enable = true

log.to = "console"
# trace, debug, info, warn, error
log.level = "trace"
log.maxDays = 3

[[proxies]]
name = "{{ .Envs.FRP_PROXY_NAME }}"
type = "tcp"
transport.useEncryption = true
transport.useCompression = true
localIP = "127.0.0.1"
localPort = {{ .Envs.LOCAL_PORT }}
remotePort = {{ .Envs.REMOTE_PORT }}